appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: kKOZjWlSB4zUt5jE5Jw0SEWfySq3jwWOY5ox9iYudx/+bEHGs2rZKiYC9QNcxV79Sb9W/z2qkwIm/5ItPMPDwCliPeH4F7UR5r/HzS3ls74veaefIIQd4NSqmLv5cXIfpMCP54PxMvZlTxcKCcDVDx/wPdodoLsEImb0bAQ0kzPKalgTUA7xNTddSsltmUtsmVlpKpZRTzqjMyeeRojspX9YQkqpKuajmXp2A8VbanSTPHgd56R1vzQWBFGlKBSTlP7pV/jM8jWx825YVz41bZ4lJiDHj0eQVjCs/okfJwdcTw0AmFohZdJG8lX3LDByeMuzDGSUYgM9LX93HmmqSzotIuSRaK+dj3OY6o8fyiXBpC4MBdvd2uTLfZTBqR8k8B3mN2jrrecYlUp66IeTDqpHX+zyBJ0g1RS1zpaR4ybiKzd9dGm3Qc8CoN+mq/7HVnt8qAnuIwleBVQqkYGO8iL1UQ8wmiBnbZ/38cYj2rCeM0R8Ijq95us9urroS8HzBgAMtJuBd8vT6Gh+PjyTew14YoWSegjfvK+gzNGQE3lIi4L3PnxoSTOmoGqtoRHo4wSec5wuP4OoAhWMpwdEpPWZYbmFDtaBEjzu7KlS6BkIOCnqcS8T/iK8LM+qyh1tybCVD6nFi220D1YnMvTZUwcgBeZUXFa5Gjuc3HMIPvY=
